// This file handles metadata and layout rendering
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Use the default RootLayout export below
export { default } from './RootLayout';
